version: '3.7'

services:
  bigdata_db: 
    image: postgres:17.4
    container_name: bigdata_db
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    volumes:
      - bigdata_volume:/data/postgres

volumes:
  bigdata_volume: